# Generated by Django 6.0.4 on 2026-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mcqs',
            field=models.TextField(blank=True),
        ),
    ]
